apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.27.0
appVersion: 4.17.0-20240123
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
dependencies:
- repository: https://kedacore.github.io/charts
  version: 2.13.0
  name: keda
  condition: autoscaling.enabled
- repository: https://kubernetes.github.io/ingress-nginx
  version: 4.9.0
  name: ingress-nginx
  condition: ingress-nginx.enabled
maintainers:
  - name: SeleniumHQ
    email: selenium-developers@googlegroups.com
sources:
  - https://github.com/SeleniumHQ/docker-selenium
