apiVersion: v1
entries:
  selenium-grid:
  - apiVersion: v2
    appVersion: 4.8.3-20230403
    created: "2023-04-19T11:46:25.72675606+02:00"
    description: A Helm chart for creating a Selenium Grid Server in Kubernetes
    digest: 5f367a95aba654bd9b16868db2952250aae28bb2df8efe97c88006563c213fe6
    icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
    name: selenium-grid
    type: application
    urls:
    - selenium-grid-0.15.7.tgz
    version: 0.15.7
generated: "2023-04-19T11:46:25.724865773+02:00"
