apiVersion: v2
entries:
  selenium-grid:
  - appVersion: 4.5.3-20221024
    description: A Helm chart for creating a Selenium Grid Server in Kubernetes
    name: selenium-grid
    sources:
    - https://github.com/SeleniumHQ/docker-selenium/tree/trunk/charts/selenium-grid
    urls:
    - selenium-grid.tgz
    version: 4.5.3-20221024
